In [87]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import json
import datetime as dt
df = pd.read_json("https://data.police.uk/api/stops-force?force=cleveland&date=2020-07")

In [88]:
df.head()

,age_range,outcome,involved_person,self_defined_ethnicity,gender,legislation,outcome_linked_to_object_of_search,datetime,removal_of_more_than_outer_clothing,outcome_object,location,operation,officer_defined_ethnicity,type,operation_name,object_of_search
0,None,A no further action disposal,True,None,None,Misuse of Drugs Act 1971 (section 23),1.0,2020-07-19 23:00:00+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.565733', 'street': {'id': 591...",NaN,None,Person and Vehicle search,NaN,Controlled drugs
1,25-34,,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),1.0,2020-07-21 14:15:10+00:00,NaN,"{'id': '', 'name': ''}","{'latitude': '54.564501', 'street': {'id': 591...",NaN,White,Person search,NaN,Controlled drugs
2,10-17,A no further action disposal,True,None,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-21 14:15:30+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.561109', 'street': {'id': 591...",NaN,None,Person and Vehicle search,NaN,Controlled drugs
3,18-24,Khat or Cannabis warning,True,Other ethnic group - Not stated,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-27 17:18:25+00:00,NaN,"{'id': 'bu-khat-or-cannabis-warning', 'name': ...",None,NaN,Other,Person search,NaN,Controlled drugs
4,10-17,A no further action disposal,True,None,Female,Misuse of Drugs Act 1971 (section 23),1.0,2020-07-06 19:20:50+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.673891', 'street': {'id': 595...",NaN,None,Person search,NaN,Controlled drugs

In [89]:
df.tail()

,age_range,outcome,involved_person,self_defined_ethnicity,gender,legislation,outcome_linked_to_object_of_search,datetime,removal_of_more_than_outer_clothing,outcome_object,location,operation,officer_defined_ethnicity,type,operation_name,object_of_search
539,over 34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-07-31 19:20:35+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.704202', 'street': {'id': 596...",NaN,White,Person search,NaN,Offensive weapons
540,None,A no further action disposal,True,None,None,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-31 22:23:30+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,None,Person and Vehicle search,NaN,Controlled drugs
541,25-34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-31 22:23:30+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Controlled drugs
542,25-34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-07-31 22:23:40+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.681800', 'street': {'id': 595...",NaN,White,Person search,NaN,Article for use in theft
543,18-24,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-31 22:23:48+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Controlled drugs

In [90]:
df.sort_values(by = "datetime", ascending = True, inplace = True)

In [91]:
df.head()

,age_range,outcome,involved_person,self_defined_ethnicity,gender,legislation,outcome_linked_to_object_of_search,datetime,removal_of_more_than_outer_clothing,outcome_object,location,operation,officer_defined_ethnicity,type,operation_name,object_of_search
19,over 34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,None,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-07-01 00:01:16+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Articles for use in criminal damage
20,over 34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-07-01 01:02:53+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Article for use in theft
21,10-17,A no further action disposal,True,Mixed/Multiple ethnic groups - Any other Mixed...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-07-01 02:03:12+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.576056', 'street': {'id': 592...",NaN,Other,Person search,NaN,Offensive weapons
22,25-34,Arrest,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),1.0,2020-07-01 02:03:30+00:00,NaN,"{'id': 'bu-arrest', 'name': 'Arrest'}",None,NaN,White,Person search,NaN,Stolen goods
23,25-34,Arrest,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),1.0,2020-07-01 02:03:36+00:00,NaN,"{'id': 'bu-arrest', 'name': 'Arrest'}",None,NaN,White,Person search,NaN,Stolen goods

In [92]:
df.tail()

,age_range,outcome,involved_person,self_defined_ethnicity,gender,legislation,outcome_linked_to_object_of_search,datetime,removal_of_more_than_outer_clothing,outcome_object,location,operation,officer_defined_ethnicity,type,operation_name,object_of_search
539,over 34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-07-31 19:20:35+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.704202', 'street': {'id': 596...",NaN,White,Person search,NaN,Offensive weapons
540,None,A no further action disposal,True,None,None,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-31 22:23:30+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,None,Person and Vehicle search,NaN,Controlled drugs
541,25-34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-31 22:23:30+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Controlled drugs
542,25-34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-07-31 22:23:40+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.681800', 'street': {'id': 595...",NaN,White,Person search,NaN,Article for use in theft
543,18-24,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-07-31 22:23:48+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Controlled drugs

In [93]:
df.describe()

,outcome_linked_to_object_of_search,removal_of_more_than_outer_clothing,operation,operation_name
count,122.000000,0.0,0.0,0.0
mean,0.836066,NaN,NaN,NaN
std,0.371743,NaN,NaN,NaN
min,0.000000,NaN,NaN,NaN
25%,1.000000,NaN,NaN,NaN
50%,1.000000,NaN,NaN,NaN
75%,1.000000,NaN,NaN,NaN
max,1.000000,NaN,NaN,NaN

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 544 entries, 19 to 543
Data columns (total 16 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   age_range                            477 non-null    object
 1   outcome                              544 non-null    object
 2   involved_person                      544 non-null    bool
 3   self_defined_ethnicity               440 non-null    object
 4   gender                               475 non-null    object
 5   legislation                          539 non-null    object
 6   outcome_linked_to_object_of_search   122 non-null    float64
 7   datetime                             544 non-null    datetime64[ns, UTC]
 8   removal_of_more_than_outer_clothing  0 non-null      float64
 9   outcome_object                       544 non-null    object
 10  location                             266 non-null    object
 11  operation                            0 non-null      float64
 12  officer_defined_ethnicity            416 non-null    object
 13  type                                 544 non-null    object
 14  operation_name                       0 non-null      float64
 15  object_of_search                     527 non-null    object
dtypes: bool(1), datetime64[ns, UTC](1), float64(4), object(10)
memory usage: 68.5+ KB

In [95]:
r = requests.get("https://data.police.uk/api/stops-force?force=cleveland&date=2020-06")
x = r.json()
dff = pd.read_json(json.dumps(x))

In [96]:
dff.head()

,age_range,outcome,involved_person,self_defined_ethnicity,gender,legislation,outcome_linked_to_object_of_search,datetime,removal_of_more_than_outer_clothing,outcome_object,location,operation,officer_defined_ethnicity,type,operation_name,object_of_search
0,over 34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-06-03 13:14:35+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Controlled drugs
1,over 34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Misuse of Drugs Act 1971 (section 23),NaN,2020-06-01 02:03:40+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...","{'latitude': '54.567601', 'street': {'id': 591...",NaN,White,Person and Vehicle search,NaN,Controlled drugs
2,over 34,Arrest,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-06-01 03:04:05+00:00,NaN,"{'id': 'bu-arrest', 'name': 'Arrest'}",None,NaN,White,Person search,NaN,Article for use in theft
3,over 34,Arrest,True,White - English/Welsh/Scottish/Northern Irish/...,Male,Police and Criminal Evidence Act 1984 (section 1),NaN,2020-06-01 03:04:21+00:00,NaN,"{'id': 'bu-arrest', 'name': 'Arrest'}",None,NaN,White,Person search,NaN,Article for use in theft
4,over 34,A no further action disposal,True,White - English/Welsh/Scottish/Northern Irish/...,Female,Misuse of Drugs Act 1971 (section 23),NaN,2020-06-01 12:13:00+00:00,NaN,"{'id': 'bu-no-further-action', 'name': 'A no f...",None,NaN,White,Person search,NaN,Controlled drugs

In [104]:
df = pd.read_json("https://data.police.uk/api/stops-force?force=cleveland&date=2020-07")
df = pd.DataFrame(df)
df.head()
df.sort_values(by = "datetime", ascending = True, inplace = True)
#df.involved_person.astype(str)
#cleveland_SS = df.involved_person.astype(str).contains(True)
cleveland_SS = len(df["involved_person"])
total = print(cleveland_SS)
dfff = df.groupby("age_range")
dfff.head()

dfff.plot(kind = "line", x = "age_range", y = "officer_defined_ethnicity")
#cleveland_SS = df.involved_person.str.contains("True")
# #print(len(cleveland_SS))

544

KeyError: 'age_range'

In [98]:
df.age_range.unique()

array(['over 34', '10-17', '25-34', '18-24', None], dtype=object)

In [84]:
police = requests.get("https://data.police.uk/api/stops-force?force=cleveland&date=2020-07")
print(police.statuscode)

In [100]:
df.plot(kind = "line", x = "age_range", y = "officer_defined_ethnicity")

TypeError: no numeric data to plot